---
- name: Check if Consul is already installed
  stat: path=/usr/bin/consul
  register: consul_installed
  
- name: Download Consul archive
  get_url: url={{ consul_binary }} dest=/tmp/consul.zip mode=0755
  when: (consul_installed.stat.exists == false)
  
- name: Unarchive Consul binary
  unarchive:
    src: /tmp/consul.zip
    dest: /usr/bin
    remote_src: true
    mode: a+x
  when: (consul_installed.stat.exists == false)

- name: Create directory for configs
  file:
    path: /etc/consul.d
    state: directory
    mode: a+w
  when: (consul_installed.stat.exists == false)
  
- name: Copy Config
  copy: "src={{ ansible_hostname }}.json dest=/etc/consul.d/consul.json force=yes"
  
- name: Create logfile
  file:
    path: /var/log/consul.log
    state: touch
    owner: root
    group: root
    mode: a+w

- name: Start Consul
  shell: "nohup consul agent --config-dir /etc/consul.d/consul.json > /var/log/consul.log 2>&1 &"
