- name: Download Fabio binary
  get_url: 
    url: "https://github.com/eBay/fabio/releases/download/v1.4.2/fabio-1.4.2-go1.8.1-linux_amd64"
    dest: /usr/bin/
    mode: a+x
    checksum: "sha256:d13e503d4f570d1c834dcbe8febd1fcffc474fe1f046dfe1e8bb04914187dabc"
  when: ansible_hostname == 'nomad-server1' 

- name: Create logfile
  file:
    path: /var/log/fabio.log
    state: touch
    owner: root
    group: root
    mode: a+w
  when: ansible_hostname == 'nomad-server1' 

- name: Start Fabio
  shell: "nohup fabio-1.4.2-go1.8.1-linux_amd64 > /var/log/fabio.log 2>&1 &"
  when: ansible_hostname == 'nomad-server1' 
