---
- hosts: all
  remote_user: vagrant
  become: yes
  roles:
    - common
#    - firewall ---configuring firewall rules Not ready yet
    - docker
    - consul
    - nomad
#    - deploy ---run Fabio as a Nomad job Not ready yet
